name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:22.8.13.20-alpine
        ports:
          - 8123:8123
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.3"
          otp-version: "25.2.3"

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ github.head_ref || github.ref }}-
            ${{ runner.os }}-mix-refs/heads/master-

      - name: Install Clickouse cli tools
        run: curl https://clickhouse.com/ | sh

      - name: Add Clickhouse cli tools to path
        run: echo "${HOME}/clickhouse" >> $GITHUB_PATH
      

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1 


      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
      # - run: INTEGRATION=1 mix test
